### ISSUE TITLE
password encryption

### ISSUE THREAD

**Issue by aws0jam** [MrLetsplay2003/WebinterfaceAPI#2]
Hello! Is it somehow possible to replace the password encryption to bcrypt?

**Comment by MrLetsplay2003** [comment]
Transferred to the WebinterfaceAPI, as this is implemented here.

This is currently not supported, however it could be added by adding a config option to the WebinterfaceAPI and then using that in the `hash` methods [here](https://github.com/MrLetsplay2003/WebinterfaceAPI/blob/f74771f693100c5e7f6adf1d5f51e045410204ed/WebinterfaceAPI/src/main/java/me/mrletsplay/webinterfaceapi/auth/SQLCredentialsStorage.java#L87C17-L87C21) and [here](https://github.com/MrLetsplay2003/WebinterfaceAPI/blob/f74771f693100c5e7f6adf1d5f51e045410204ed/WebinterfaceAPI/src/main/java/me/mrletsplay/webinterfaceapi/auth/FileCredentialsStorage.java#L61) (these methods should probably be merged into one) to determine the hashing method to use.

I would have to add another crypto library for that though

**Comment by aws0jam** [comment]
thank you!
